import "../assets/css/style.css"
export const metadata = {
  title:{
    default:"next.js",
    template:"%s create with amir"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
